project:
  type: website
  output-dir: docs

website:
  title: "Joshua Mull"
  navbar:
    title: false
    logo: "logos/2560x1440.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
      - text: Resources 
      - posts.qmd
      

format:
  html:
    theme: styles.scss
    mainfont: Sixtyfour Convergence
    toc: False
    page-layout: full



