project:
  type: website
  output-dir: docs

website:
  title: "Joshua Mull"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      

format:
  html:
    theme: simplex
    css: styles.css
    toc: False
    page-layout: full



